# Generated by Django 5.2.6 on 2025-09-28 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('overview', models.TextField(help_text='Overview points separated by newlines')),
                ('benefits', models.TextField(help_text='Benefits points separated by newlines')),
                ('image_overview', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('image_benefits', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='certificates.certificate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
