# Generated by Django 5.2.6 on 2025-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='assessments',
            field=models.TextField(blank=True, help_text='Assessment methods separated by newlines'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='objectives',
            field=models.TextField(blank=True, help_text='Learning objectives separated by newlines'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='outcomes',
            field=models.TextField(blank=True, help_text='Learning outcomes separated by newlines'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle for the certificate', max_length=200),
        ),
    ]
